name: Build and publish seichiassist-runner docker image
on:
  push:
    branches:
    - master
    paths:
    - 'seichiassist-runner/**' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Publish Docker Image to GPR
        uses: machine-learning-apps/gpr-docker-publish@master
        id: docker
        with:
          IMAGE_NAME: 'seichiassist-runner'
          DOCKERFILE_PATH: './seichiassist-runner/Dockerfile'
          BUILD_CONTEXT: './seichiassist-runner'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
