name: Build and publish seichiassist-runner docker image
on:
  push:
    branches:
      - master
    paths:
      - 'SeichiAssist/runner/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Publish seichiassist-runner Docker Image to GPR
        uses: machine-learning-apps/gpr-docker-publish@master
        id: docker
        with:
          IMAGE_NAME: 'seichiassist-runner'
          DOCKERFILE_PATH: './SeichiAssist/runner/Dockerfile'
          BUILD_CONTEXT: './'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
