name: Build and publish seichiassist-builder docker image
on:
  push:
    branches:
    - master
    paths:
    - 'seichiassist-builder/**'
    - '.github/workflows/publish-seichiassist-builder.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      image_name: seichiassist-builder

    # 参考: https://qiita.com/kawakawaryuryu/items/b0291c1bc1141a535263
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - id: lowercase_image_id
        name: Make image id lowercase
        run: |
          image_id=ghcr.io/${{ github.repository_owner }}/${{ env.image_name }}
          echo "::set-output output=$(echo $image_id | tr '[A-Z]' '[a-z]')"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ steps.lowercase_image_id.outputs.output }}:latest
            ${{ steps.lowercase_image_id.outputs.output }}:1.0.0
